# Generated by Django 3.1.3 on 2022-06-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_questioncount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionCount',
        ),
    ]
