# Generated by Django 3.1.3 on 2022-06-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_auto_20220610_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='hit',
            new_name='hits',
        ),
    ]
