# Generated by Django 3.1.3 on 2022-06-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_auto_20220610_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hits',
        ),
    ]
