# Generated by Django 3.1.3 on 2022-06-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0013_questioncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
